main: ${project.groupId}.${java.package.id}.${project.name}
name: ${project.name}
author: SyntaxPhoenix IT-Solutions
version: ${projectVersion}
api-version: 1.13
softdepend: [BlockyLog, WorldGuard, Residence, Lands, Jobs, GriefPrevention, PlaceholderAPI, CoreProtect, LogBlock, mcMMO, Towny]

commands:
    smoothtimber:
        description: SmoothTimber main command
        aliases: [sm, stimb]
        usage: &cSomething went wrong while running this command, please report this to developer.
        
permissions:
    smoothtimber.*:
        description: Gives access to all SmoothTimber permissions
        children:
            smoothtimber.limit.*: true
            smoothtimber.use: true
            smoothtimber.toggle: true
    smoothtimber.limit.*:
        description: Allows you to break unlimited blocks if the limiter is enabled
        default: op
    smoothtimber.use:
        description: Allows you to use SmoothTimber
        default: true
    smoothtimber.toggle:
        description: Allows you to toggle the TreeCutter of SmoothTimber
        default: true
